[package]
name = "crystal-caverns"
version = "0.0.2-alpha"
edition = "2024"

[dependencies]
# Latest Lua, 5.4 :D
mlua = { version = "0.10.3", features = ["lua54", "vendored"] }
# Raylib because - we're using rl
raylib = "5.5.1"
# rfd, primarily for error handling
rfd = "0.15.3"
